### ISSUE TITLE
webworks build broken (debug, device)

### ISSUE THREAD

**Issue by jsoref** [blackberry/webworks-gui#221] opened 2014-04-28 20:20 UTC
#207 has broken the default workflow:
1. create project
2. click Build
3. click BUILD

Actual results:
animated building... and then it goes away, nothing is built.

On OS X, there's "error: option '-k, --keystorepass <password>' argument missing"
On Windows XP, there's no output.

**Comment by jamesjhedley** [comment] 2014-04-28 21:47
@rcruz and i were looking into this.

It seems as though --keystorepass with an empty string does NOT actually prevent prompting like it does for --devicepass. In the GUI it prompts/hangs (release builds with no keystore pass or run with no keystore pass).

In my opinion there is also another issue here. Although it works as intended, i feel as though providing an empty string for --devicepass to prevent prompting is incorrect, since what it's actually doing is attempting to authenticate with the device with an incorrect password. Do this enough times and ur device get's wiped? Seems wrong. I understand the issue we are trying to resolve (prompting) just not sure this is the way to solve it.

**Comment by rcruz** [comment] 2014-04-28 22:00
This is the current observed behaviour on OSX:

webworks build --keystorepass "" 
- No prompt on terminal
- Builds succeeds, displays in GUI correctly

webworks build --release --keystorepass "" 
- Prompts for keystore pass on terminal
- Build hangs on prompt, GUI hangs waiting for CLI

webworks run --keystorepass ""
- Prompts for keystore pass on terminal
- Build hangs on prompt, GUI hangs waiting for CLI

webworks run --release --keystorepass ""
- Prompts for keystore pass on terminal
- Build hangs on prompt, GUI hangs waiting for CLI

This shows that preventing terminal prompts cannot be achieved in all cases by passing --keystorepass "" to webworks CLI

**Comment by jsoref** [comment] 2014-04-28 22:32
```
$ webworks build  --release --keystorepass "" --no-query
No signing password provided. You can omit --no-query, use --no-signing, use --keystorepass, or enter a value for 'keystorepass' in /Users/jsoref/.cordova/blackberry10.json

$ webworks build  --release --no-query
No signing password provided. You can omit --no-query, use --no-signing, use --keystorepass, or enter a value for 'keystorepass' in /Users/jsoref/.cordova/blackberry10.json

$ webworks run --no-query --release --devicepass $PASSWORD
 Device is not in the Development Mode. Switch to Development Mode from Security settings on the device.

$ webworks run --no-query --devicepass $PASSWORD
 Device is not in the Development Mode. Switch to Development Mode from Security settings on the device.
```

**Comment by bryanhiggins** [comment] 2014-04-29 01:47
Moving to 2.1 milestone

We were originally going to check if project version > 3.4 for the --no-query option. It was decided it was easier to pass default values for keystorepass and devicepass. It appears that is not the case.

**Comment by bryanhiggins** [comment] 2014-04-29 13:58
Here is my proposal: #224

**Comment by jamesjhedley** [comment] 2014-04-29 14:16
I strongly recommend that for this release we at least make --keystorepass behave as --devicepass does (support for "" without hanging). I would rather it attempt to sign/generate a debug token with an incorrect keystorepass ("") then hang in the GUI. Hanging = gating in my opinion.

**Comment by bryanhiggins** [comment] 2014-04-29 14:19
@jkeshavarzi we all agree on that (I hope)

There is no hanging with my patch applied.

**Comment by jamesjhedley** [comment] 2014-04-29 14:23
@bryanhiggins Good good. Sorry, It sounded as though we may leave this for a future milestone. I misunderstood. Glad we are addressing it :).

**Closed as completed** 2014-04-29 14:42 UTC
