### ISSUE TITLE
 As a WebWorks developer, I can open an existing project in the GUI tool 

### ISSUE THREAD

**Issue by kwallis** [blackberry/webworks-gui#15] opened 2014-01-13 17:46 UTC
## Acceptance Criteria
- Add "Open project" to the navigation above list of the projects
- The open project button should have a tool tip saying "Open existing project"
- New project model should be created based on given filepath
- Config page of the project should be displayed after importing

Old details:
- Test isValidProject() function
- Validate whether it is a project cordova
- Save the project in web storage (Use webstorage-manager.js)
- Put the project in the list of UI

**Comment by rwmtse** [comment] 2014-01-14 03:59
@kwallis @bryanhiggins @rcruz 
How does the user specify the project path? Through a text field? (Remember I had trouble with the file input) Please be more specific regarding the expected UI

**Comment by kwallis** [comment] 2014-01-15 16:50
UI can be the same as the create page, though no need for the PRoject Name field. Textbox to accept the path.

**Comment by rwmtse** [comment] 2014-01-16 02:31
@kwallis If the project name field is omitted, what should I use for Project Name in the GUI?

Currently Project Name is specified in the GUI at project creation time, and it's not tied to the "App Name" in config.xml.

Or, do you want to set the Project Name to the last part of the Project Path?

**Comment by kwallis** [comment] 2014-01-16 03:18
Ah, OK, didn't realize it was not tied to config.xml app name. Let's keep the project name field then.

**Comment by rwmtse** [comment] 2014-01-16 05:13
@kwallis Alright, didn't notice you replied 2 hours ago. Thanks Ken.

**Comment by bryanhiggins** [comment] 2014-01-16 14:29
@kwallis  There shouldn't be a "Project Name" that isn't tied to config.xml. 

The create command accepts ID and name. Both of those should be passed from the GUI create screen.

When opening a project, the name should be read from config.

**Comment by rwmtse** [comment] 2014-01-16 14:33
Does this mean the project create view should change?

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Bryan Higgins
Sent: Thursday, January 16, 2014 9:29 AM
To: blackberry/webworks-gui
Reply To: blackberry/webworks-gui
Cc: Rosa Tse
Subject: Re: [webworks-gui] As a WebWorks developer, I can open an existing project in the GUI tool (#15)

@kwallishttps://github.com/kwallis There shouldn't be a "Project Name" that isn't tied to config.xml.

The create command accepts ID and name. Both of those should be passed from the GUI create screen.

When opening a project, the name should be read from config.

—
Reply to this email directly or view it on GitHubhttps://github.com/blackberry/webworks-gui/issues/15#issuecomment-32472996.

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by rcruz** [comment] 2014-01-16 15:43
Project create view should not change. The view for "open project" should be a similar page to project create, but with only one text field for the path of the existing project.

**Comment by rwmtse** [comment] 2014-01-16 15:47
My comment is related to the discussion about the project name currently now tie to App Name in config.xml

If opening existing project uses app name for project name, then create project should also tie the project name to app name.

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Rowell Cruz
Sent: Thursday, January 16, 2014 10:43 AM
To: blackberry/webworks-gui
Reply To: blackberry/webworks-gui
Cc: Rosa Tse
Subject: Re: [webworks-gui] As a WebWorks developer, I can open an existing project in the GUI tool (#15)

Project create view should not change. The view for "open project" should be a similar page to project create, but with only one text field for the path of the existing project.

**Comment by rcruz** [comment] 2014-01-16 15:54
The project name in the create page is stored as < widget id="<project name>" > in config.xml. That value is used as the project name in the side list

**Comment by rwmtse** [comment] 2014-01-16 16:04
Oh ok, now it's clear. Thanks Rowell.

**Comment by rcruz** [comment] 2014-02-10 18:10
Closed by https://github.com/blackberry/webworks-gui/pull/45

**Closed as completed by rcruz** 2014-02-10 18:10 UTC
Labels: Feature, UX Review
