### ISSUE TITLE
When deleting the last target the UI does not update itself to show that it has been deleted

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#159] opened 2014-04-16 18:33 UTC
When you delete the last target, the UI does not update itself to show that it has been updated. You keep on clicking on the delete button and it appears it does something for a moment but you still see the target. It's until you click on a different tab and then go back that you see there's nothing left.

**Comment by rcruz** [comment] 2014-04-20 02:46
Not reproducible on OSX 10.6. Where is this happening?

**Comment by rcruz** [comment] 2014-04-20 03:06
Exists on build 2.1.0.5, however cannot be reproduced on master branch.

**Comment by rcruz** [comment] 2014-04-22 16:20
Closing since it appears to be fixed.

**Closed as completed by rcruz** 2014-04-22 16:20 UTC
Labels: Bug

**Comment by jengee** [comment] 2014-04-22 16:21
Agreed. Works now in 2.1.0.7.
